### PR TITLE
Avoid debug firebase dependency

### PR DESCRIPTION
**Pull request by yschimke**
Don't assume Firebase is setup in debug builds

### CODE REVIEW

**Comment by martinbonnin** [comment]
No committing of the google-services.json then?

**Comment by yschimke** [comment]
@martinbonnin This seemed like a good change anyway. Not a vote either way.

**Comment by martinbonnin** [comment]
👍 Asking cause I'm starting to think about Bookmarks that will require Firebase auth at some point. I might commit a google-services.json at that point so that someone cloning the repo would still be able to use the feature.

**Comment by yschimke** [comment]
What about a test only instance, leave the production one separate?

**Comment by martinbonnin** [comment]
That should work 👍

**Pull request merged**
