### PR TITLE
Create ConfettiIcons pack and migrate to ImageVector

### PR DESCRIPTION
**Pull request by egorikftp**
I used https://github.com/ComposeGears/Valkyrie to migrate existing xml icons into Compose ImageVector

Also:

- Migrated from `Image` to `Icon` to automatically apply tint color
- Remove unused resources
- Remove `materialIconsExtended` dependency

### CODE REVIEW

**Comment by egorikftp** [comment]
@martinbonnin could you please approve github action workflow to check if everything ok? 🙂 

image

**Review by martinbonnin — APPROVED** [review]
LGTM 
I'll defer to @joreilly for the merging

**Comment by joreilly** [comment]
@egorikftp thanks for the PR.  What's the advantage of this approach?  It looks like we're replacing fairly standard resources with custom Compose code?

**Comment by egorikftp** [comment]
@joreilly 
Using ImageVector instead XML allow to skip parsing phase for each icon. Also we faced better performance during icon animations in our apps.

More details:
https://medium.com/@farbod.bijary/imagevector-vs-xml-drawable-a-performance-guide-fbad5135bbe8

**Pull request merged**
