### PR TITLE
Add bookmarks to tablet session view

### PR DESCRIPTION
**Pull request by oas004**
Also I added the bookmark top level destination to the navigation rail. I'm not 100% sure about the design on this, so I'm leaving it a draft PR :) I also would like to add some robolectric tests to test the compose logic if that is okay? :) 

This relates to #382 

Here is what it looks like now:

image
image

If u have not signed in and clicks the bookmark
image

### CODE REVIEW

**Comment by oas004** [comment]
Is it only wear that has robolectric tests? :) Can I add that for the Android app side?

**Comment by joreilly** [comment]
That looks good....I think only concern I had before about putting in that position is if the name is very long (ran in to that elsewhere).  @martinbonnin what do you think?

**Comment by martinbonnin** [comment]
What about something like hoverboard? https://hoverboard-master.web.app/schedule/2016-09-10

Screenshot 2023-04-04 at 10 55 47

Align title left and put the bookmark on the line below aligned right? We don't have tags/level for sessions but that might still work.

**Comment by oas004** [comment]
Wow! That looks cool! I can try to implement that! 🙌

**Comment by oas004** [comment]
Might be me that is doing this wrong, but should the title have some max line and truncate after that? If the title is very long I get an issue with the spacing for the speakers. Wdyt? In the design above they are truncating it, but that is a description so maybe that is a bit different 🤔 
This is the issue: 
image

**Comment by oas004** [comment]
Yeah, I agree! :) Here I have increased the card size some. Wdyt? 

Here it is with the static CenterEnd align
image

Here it is in the column as an element between
image

**Comment by oas004** [comment]
Is there a limit on how many users that can speak at one talk? :)

**Comment by oas004** [comment]
So something like this if it is more than 3? In this case it had a lot of padding since the title is not very large 🤔 
image

**Comment by martinbonnin** [comment]
Agree, feels weird. Maybe 2 x 2 + ellipsis?

**Comment by oas004** [comment]
Maybe this makes it better, as a FlowRow with 2 items max in each row 🤔 
image

**Comment by martinbonnin** [comment]
> Maybe this makes it better, as a FlowRow with 2 items max in each row 🤔

I was thinking with names. 

```
[pic] name                  [pic] name2
[pic] other long na..   [pic] name3
```

But design review over GitHub is hard! Feel free to choose the one you like best and then we can iterate during KotlinConf :)

**Comment by oas004** [comment]
> Agree, feels weird. Maybe 2 x 2 + ellipsis?

Yeah, I think that can work 🤔

**Comment by oas004** [comment]
> > Maybe this makes it better, as a FlowRow with 2 items max in each row 🤔
> 
> I was thinking with names.
> 
> ```
> [pic] name                  [pic] name2
> [pic] other long na..   [pic] name3
> ```
> 
> But design review over GitHub is hard! Feel free to choose the one you like best and then we can iterate during KotlinConf :)

Yeah I agree! Sadly I didn't order tickets in time for that :( But I'll be watching the stream! 🙌

**Comment by martinbonnin** [comment]
Oh no! I was looking forward to catchup! Well, just in case you want to visit Paris in Spring 🌸 , [Android Makers](https://androidmakers.droidcon.com/tickets/) is a couple of weeks later and still has tickets :)

**Comment by oas004** [comment]
Yeah that would have definitely been cool! 🤩

**Comment by oas004** [comment]
I would like to add Robolectric tests for this PR. Is it only wear that has any robolectric tests? Can I configure that for Android as well? :)

**Comment by martinbonnin** [comment]
Yup, I think there's nothing on mobile yet, go for it.

**Pull request merged**
