### PR TITLE
Add a basic baseline profile for Wear

### PR DESCRIPTION
**Pull request by yschimke**
Just the most basic, startup the app and let it do the initial API request.

### CODE REVIEW

**Comment by joreilly** [comment]
Nice!  I'll publish new version to play store once this is merged (you probably saw I assume the merge conflicts due to previous merges).

**Comment by yschimke** [comment]
Let me add for mobile as well.

**Comment by yschimke** [comment]
Just noticed the baseline profile is in wrong directory.

**Comment by joreilly** [comment]
ok, will hold off merging until that's change is included

**Comment by yschimke** [comment]
I think good to go.

**Pull request merged**
