### PR TITLE
Add Devfest Nantes 2024

### PR DESCRIPTION
**Pull request by ArtyMaury**

### CODE REVIEW

**Comment by joreilly** [comment]
@ArtyMaury looks like we're having issue parking https://raw.githubusercontent.com/GDG-Nantes/Devfest2024/main/ when importing.... cc @martinbonnin

**Comment by joreilly** [comment]
failing on 2nd line below line it seems in `DevFestNantes.kt`

```        var sessions = listYamls("data/sessions").mapNotNull { session ->
            val talk = Yaml.default.parseToYamlNode(getGithubFile(session)).toAny().asMap
```

Screenshot 2024-08-21 at 16 18 13

**Comment by martinbonnin** [comment]
Looks like it was fixed [here](https://github.com/GDG-Nantes/Devfest2024/commit/2fc7d875be3c2e99b72f4fd12bad81dfd0d94765)?

**Comment by martinbonnin** [comment]
```
$ curl -X POST https://confetti-app.dev/update/devfestnantes2024
Oooopsie%                            
```

Looks like there's something else, I'll dig

**Comment by martinbonnin** [comment]
Fixed in https://github.com/joreilly/Confetti/pull/1423

**Pull request merged**
