### PR TITLE
Add Confetti project icon

### PR DESCRIPTION
**Pull request by yschimke**
Shows up when opening projects in Android Studio
image

### CODE REVIEW

**Comment by yschimke** [comment]
@joreilly just converted from the png, but if you have a clean SVG we should update.

**Comment by joreilly** [comment]
@martinbonnin has svg version I think

**Comment by yschimke** [comment]
I might land and update, rather than coordinating on this PR.

**Comment by martinbonnin** [comment]
Follow up there: https://github.com/joreilly/Confetti/pull/495

FWIW, the design sources are under `design`. Currently they are .sketch files cause some masking transformations do not work well in SVG

**Pull request merged**
