### PR TITLE
Use roborazzi for screenshots

### PR DESCRIPTION
**Pull request by yschimke**
Drop quickbird, use roborazzi.

This won't actually run on CI automatically, I will follow up with the workflow changes to activate.

### CODE REVIEW

**Comment by yschimke** [comment]
cc @oas004 - didn't see much uptake so I didn't keep the A11y test.  It would be trivial to do so.

**Comment by yschimke** [comment]
Test only

**Comment by oas004** [comment]
> cc @oas004 - didn't see much uptake so I didn't keep the A11y test. It would be trivial to do so.

I think that is fine, sorry for not being that active in this lately. Have a bit much on my plate at work lately :(

**Comment by yschimke** [comment]
@oas004 I have zero expectations of your time, you never need to apologise.

**Pull request merged**
