### PR TITLE
Fix Google signin on some devices

### PR DESCRIPTION
**Pull request by martinbonnin**
Google signin fails on my device with `GetCredentialResponse returned from framework`:

```
CredManProvService      dev.johnoreilly.confetti             I  GetCredentialResponse returned from framework
System.out              dev.johnoreilly.confetti             I  NoCredentialException
```

and on @emartynov one with: 

```
CredManProvService      dev.johnoreilly.confetti             I  GetCredentialResponse returned from framework
System.out              dev.johnoreilly.confetti             I  Unknown auth v2.g0@5d1613b
```

It's not 100% clear what's happening under the hood but changing from `GetGoogleIdOption` to `GetSignInWithGoogleOption` fixes the issue, at least on my device:

https://github.com/joreilly/Confetti/assets/3974977/ec3dabe0-612c-4ac8-815a-2dde6733568e

### CODE REVIEW

**Comment by joreilly** [comment]
are we ok to merge this?

**Comment by emartynov** [comment]
Sorry, people, I haven't checked my issue with this fix. But at least it fixes one from Martin.

**Comment by emartynov** [comment]
Oke, this also works for me!

**Review by emartynov — APPROVED** [review]

**Comment by martinbonnin** [comment]
Can't approve my own PR but LGTM :)

**Pull request merged**
