### PR TITLE
Make full view clickable of conference in iOS

### PR DESCRIPTION
**Pull request by percy-g2**
https://github.com/joreilly/Confetti/assets/4012000/cf10b9f0-e2f0-4e70-b854-76096137c993

### CODE REVIEW

**Comment by percy-g2** [comment]
@joreilly  please review

**Comment by percy-g2** [comment]
@joreilly any update on this?

**Comment by joreilly** [comment]
What's the issue this is fixing?  I tried both here and couldn't see difference but might be missing something

Also, can we keep this PR to just the swift changes (I'd like if possible for `SessionItemView` to only know about information relating to itself e.g. not needing full set of bookmarks to be passed to it)

**Comment by percy-g2** [comment]
> What's the issue this is fixing? I tried both here and couldn't see difference but might be missing something
> 
> Also, can we keep this PR to just the swift changes (I'd like if possible for `SessionItemView` to only know about information relating to itself e.g. not needing full set of bookmarks to be passed to it) (UPDATE: ah, I see you just did that :) )

if you click the white space in between name of conference and date, it's not clickable like we have in android the whole card view and it doesn't navigate. It fixes that.

**Comment by joreilly** [comment]
ah, ok....thanks

**Pull request merged**
