### PR TITLE
Android: Fix speaker initial and detail view UI.

### PR DESCRIPTION
**Pull request by percy-g2**
Please review the evidence.

https://github.com/joreilly/Confetti/assets/4012000/fb1ccab8-99c8-45ab-8723-757d3b8f30da

https://github.com/joreilly/Confetti/assets/4012000/0ae25569-fc79-4733-90a8-63c620f647e2

https://github.com/joreilly/Confetti/assets/4012000/58f5ab5b-344a-4ea0-82e4-90db2dbc318a

https://github.com/joreilly/Confetti/assets/4012000/f1ef1e32-55df-4482-9fd8-e4be09f688af

### CODE REVIEW

**Comment by percy-g2** [comment]
@joreilly can you check this SpeakerDetailsScA11yTest , IMO it's not needed and doesn't serve any purpose ? I might be wrong or can you help/guide me fix the test.

**Comment by joreilly** [comment]
@oas004 I think this. just requires us to create a new base screenshot based on changes....or maybe genuine issue?

**Comment by oas004** [comment]
> @oas004 I think this just requires us to create a new base screenshot based on changes....or maybe genuine issue?

I think just regenerating the base screenshots as you said should do it. But I'm not quite sure how this was setup as it's been a while since I added that. Maybe @yschimke has more information about this? :)

**Comment by oas004** [comment]
Yeah I think as @yschimke says, this was before libraries like Roborazzi (https://github.com/takahirom/roborazzi), so it's a bit homegrown. Maybe it makes sense to migrate to that? 🤔

**Comment by yschimke** [comment]
Definitely, Now In Android has roborazzi and a Github workflow to update screenshots in CI.

**Comment by percy-g2** [comment]
@joreilly not facing this test failure at my end, can you check ?

**Comment by percy-g2** [comment]
Test results 
[Test Results - Tests_in_'dev_johnoreilly_confetti_wear'.html.zip](https://github.com/joreilly/Confetti/files/13492566/Test.Results.-.Tests_in_.dev_johnoreilly_confetti_wear.html.zip)

**Comment by percy-g2** [comment]
@joreilly MR/PR is ready for your review!

**Pull request merged**
